package org.opencb.cellbase.core.common.regulatory;

// Generated Jun 5, 2012 6:41:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.List;

/**
 * RegulatoryRegion generated by hbm2java
 */
public class RegulatoryRegion implements java.io.Serializable {
    
    
    private String _id;
    private String name;
    private String alias;
    private String featureClass;
    
    private String chromosome;
    private int start;
    private int end;
    private String strand;
    
    private String source;
    private String featureType;
    private String score;
    private String frame;
    private String matrix;
    
    private List<String> chunkIds;
    private List<String> cellTypes;

        /*
        "_id" : ObjectId("51f7a0197ee4a2ea823642c7"),
        "chromosome" : "19",
        "chunkIds" : [
                "19_29",
                "19_30",
                "19_31",
                "19_32",
                "19_33",
                "19_34"
        ],
        "source" : "ccat_histone",
        "featureType" : "H3K36_trimethylation_site",
        "start" : 59050,
        "end" : 69700,
        "score" : ".",
        "strand" : ".",
        "frame" : ".",
        "name" : "H3K36me3",
        "featureClass" : "Histone",
        "alias" : "IMR90_H3K36me3_EpiRoadmap_UCSD_GSE16256_ccat_histone",
        "cellTypes" : [
                "IMR90"
        ]
        * 
        */

//	private int regulatoryRegionId;
//	private String name;
//	private String type;
//	private String chromosome;
//	private int start;
//	private int end;
//	private double experimentalScore;
//	private String cellType;
//	private String cellTypeDescription;
//	private String source;
//	private Set<Tfbs> tfbses = new HashSet<Tfbs>(0);
//
//	public RegulatoryRegion() {
//	}
//
//	public RegulatoryRegion(int regulatoryRegionId, String name, String type,
//			String chromosome, int start, int end, double experimentalScore,
//			String cellType, String cellTypeDescription, String source) {
//		this.regulatoryRegionId = regulatoryRegionId;
//		this.name = name;
//		this.type = type;
//		this.chromosome = chromosome;
//		this.start = start;
//		this.end = end;
//		this.experimentalScore = experimentalScore;
//		this.cellType = cellType;
//		this.cellTypeDescription = cellTypeDescription;
//		this.source = source;
//	}
//
//	public RegulatoryRegion(int regulatoryRegionId, String name, String type,
//			String chromosome, int start, int end, double experimentalScore,
//			String cellType, String cellTypeDescription, String source,
//			Set<Tfbs> tfbses) {
//		this.regulatoryRegionId = regulatoryRegionId;
//		this.name = name;
//		this.type = type;
//		this.chromosome = chromosome;
//		this.start = start;
//		this.end = end;
//		this.experimentalScore = experimentalScore;
//		this.cellType = cellType;
//		this.cellTypeDescription = cellTypeDescription;
//		this.source = source;
//		this.tfbses = tfbses;
//	}
//
//	public int getRegulatoryRegionId() {
//		return this.regulatoryRegionId;
//	}
//
//	public void setRegulatoryRegionId(int regulatoryRegionId) {
//		this.regulatoryRegionId = regulatoryRegionId;
//	}
//
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	public String getType() {
//		return this.type;
//	}
//
//	public void setType(String type) {
//		this.type = type;
//	}
//
//	public String getChromosome() {
//		return this.chromosome;
//	}
//
//	public void setChromosome(String chromosome) {
//		this.chromosome = chromosome;
//	}
//
//	public int getStart() {
//		return this.start;
//	}
//
//	public void setStart(int start) {
//		this.start = start;
//	}
//
//	public int getEnd() {
//		return this.end;
//	}
//
//	public void setEnd(int end) {
//		this.end = end;
//	}
//
//	public double getExperimentalScore() {
//		return this.experimentalScore;
//	}
//
//	public void setExperimentalScore(double experimentalScore) {
//		this.experimentalScore = experimentalScore;
//	}
//
//	public String getCellType() {
//		return this.cellType;
//	}
//
//	public void setCellType(String cellType) {
//		this.cellType = cellType;
//	}
//
//	public String getCellTypeDescription() {
//		return this.cellTypeDescription;
//	}
//
//	public void setCellTypeDescription(String cellTypeDescription) {
//		this.cellTypeDescription = cellTypeDescription;
//	}
//
//	public String getSource() {
//		return this.source;
//	}
//
//	public void setSource(String source) {
//		this.source = source;
//	}
//
//	public Set<Tfbs> getTfbses() {
//		return this.tfbses;
//	}
//
//	public void setTfbses(Set<Tfbs> tfbses) {
//		this.tfbses = tfbses;
//	}

    public RegulatoryRegion() {
    }

    public RegulatoryRegion(String _id, String name, String alias, String featureClass, String chromosome, int start, int end, 
            String strand, String source, String featureType, String score, String frame, String matrix,
            List<String> chunkIds, List<String> cellTypes) {
        this._id = _id;
        this.name = name;
        this.alias = alias;
        this.featureClass = featureClass;
        this.chromosome = chromosome;
        this.start = start;
        this.end = end;
        this.strand = strand;
        this.source = source;
        this.featureType = featureType;
        this.score = score;
        this.frame = frame;
        this.matrix = matrix;
        this.chunkIds = chunkIds;
        this.cellTypes = cellTypes;
    }

    public String getId() {
        return _id;
    }

    public void setId(String _id) {
        this._id = _id;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public List<String> getCellTypes() {
        return cellTypes;
    }

    public void setCellTypes(List<String> cellTypes) {
        this.cellTypes = cellTypes;
    }

    public String getChromosome() {
        return chromosome;
    }

    public void setChromosome(String chromosome) {
        this.chromosome = chromosome;
    }

    public List<String> getChunkIds() {
        return chunkIds;
    }

    public void setChunkIds(List<String> chunkIds) {
        this.chunkIds = chunkIds;
    }

    public int getEnd() {
        return end;
    }

    public void setEnd(int end) {
        this.end = end;
    }

    public String getFeatureClass() {
        return featureClass;
    }

    public void setFeatureClass(String featureClass) {
        this.featureClass = featureClass;
    }

    public String getFeatureType() {
        return featureType;
    }

    public void setFeatureType(String featureType) {
        this.featureType = featureType;
    }

    public String getFrame() {
        return frame;
    }

    public void setFrame(String frame) {
        this.frame = frame;
    }

    public String getMatrix() {
        return matrix;
    }

    public void setMatrix(String matrix) {
        this.matrix = matrix;
    }
    
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getScore() {
        return score;
    }

    public void setScore(String score) {
        this.score = score;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public int getStart() {
        return start;
    }

    public void setStart(int start) {
        this.start = start;
    }

    public String getStrand() {
        return strand;
    }

    public void setStrand(String strand) {
        this.strand = strand;
    }

    @Override
    public String toString() {
        return "RegulatoryRegion{" + "_id=" + _id + ", name=" + name + ", alias=" + alias + ", featureClass=" + featureClass 
                + ", chromosome=" + chromosome + ", start=" + start + ", end=" + end + ", strand=" + strand 
                + ", source=" + source + ", featureType=" + featureType + ", score=" + score + ", frame=" + frame 
                + ", chunkIds=" + chunkIds + ", cellTypes=" + cellTypes + '}';
    }

    
}
